cex:
  api_key: "XXXXX"
  api_secret: "YYYY"
  base_url: "https://api.binance.com"
  platform: "binance"
  kline_intervals:
    - "4h"
    - "8h"
    - "1d"
  data_path: "data"
  timezone: "Asia/Singapore"
strategies:
  Momentum:
    period: 10
    buy_threshold: 0
    sell_threshold: 0